// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fuwffhizcapskzhvjkvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1d2ZmaGl6Y2Fwc2t6aHZqa3Z3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY1ODMxNTYsImV4cCI6MjA1MjE1OTE1Nn0.GznCxx_sTEFUmnrJ3aj8KKQPk5le_aKezOO43FTbJdg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);